theme: jekyll-theme-minimal
title: Community Pages
description: Private Digital Cash. Welcome to our home! AEON is an open source project, and therefore it’s life comes from the <b>AEON community</b>; the regular people who decide to follow and help build the project.
logo: /assets/img/title_logo.svg
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
