theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge
title: AEON Coin How-To Articles
description: Here is some information related to the AEON digital currency.
logo: /assets/img/aeon_title2_340x128.png
