theme: jekyll-theme-minimal
title: AEON Community Pages
description: Various and sundry information related to the AEON digital currency
logo: /assets/img/aeon_title2_340x128.png
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
