theme: jekyll-theme-minimal
title: AEON Community Pages
description: A compilation of information, links, and recognition of Aeon accomplishments
logo: /assets/img/aeon_title2_340x128.png
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
